version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: jobs_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: apps_mongo
    restart: always
    ports:
      - "27017:27017"
